from .question4_double_fields_player import plot_double_fields_player
from .question4_double_fields_player_combined import plot_double_fields_player_combined
from .question4_averages import plot_player_average