from .question15_double_fields_player import plot_double_fields_player
from .question15_double_fields_player_combined import plot_double_fields_player_combined
from .question15_averages import plot_player_average