from .footer import add_footer
from .navigation import navigation
from .home import home
from .texts import *
from .question2_web import question2_web
from .question5_web import question5_web
from .question7_web import question7_web
from .question15_web import question15_web
from .question4_web import question4_web
from .question1_web import question1_web
from .question6_web import question6_web
from .question9_web import question9_web
from .question10_web import question10_web
from .data_pipeline_web import data_pipeline_web